version: "3.7"
services:
  flask-api:
    build:
      context: ./docker-images-flask
      dockerfile: Dockerfile
    ports:
      - 5000:80
  next-client:
    build:
      context: ./docker-images-next
      dockerfile: Dockerfile
      target: dev # 開発環境はdev、本番環境はprod（/docker-images-next/Dockerfileに記述あり）
    volumes:
      - ./docker-images-next:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - 3000:3000
    depends_on:
      - flask-api
    stdin_open: true
  postgres-db:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=POSTGRESDB
    ports:
      - 5432:5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d # docker-entrypoint-initdb.d内のスクリプトは起動時に1度だけ実行される
